# Project "koralle"
# This makefile was generated by Koralle 0.0.9

__root:  __logging___root __root-__deps __root-__core
	@ echo "[log] <koralle> ... finished '__root'"
.PHONY: __root

__logging___root: 
	@ echo "[log] <koralle> processing '__root' ..."
.PHONY: __logging___root

__root-__deps:  __logging___root-__deps
	@ echo "	[log] <koralle> ... finished '__root-__deps'"
.PHONY: __root-__deps

__logging___root-__deps: 
	@ echo "	[log] <koralle> processing '__root-__deps' ..."
.PHONY: __logging___root-__deps

__root-__core:  __logging___root-__core __root-__core-all
	@ echo "	[log] <koralle> ... finished '__root-__core'"
.PHONY: __root-__core

__logging___root-__core: 
	@ echo "	[log] <koralle> processing '__root-__core' ..."
.PHONY: __logging___root-__core

__root-__core-all:  __logging___root-__core-all __root-__core-all-link
	@ echo "		[log] <koralle> ... finished '__root-__core-all'"
.PHONY: __root-__core-all

__logging___root-__core-all: 
	@ echo "		[log] <koralle> processing '__root-__core-all' ..."
.PHONY: __logging___root-__core-all

__root-__core-all-link:  __logging___root-__core-all-link __root-__core-all-link-build build/koralle.js
	@ echo "			[log] <koralle> ... finished '__root-__core-all-link'"
.PHONY: __root-__core-all-link

__logging___root-__core-all-link: 
	@ echo "			[log] <koralle> processing '__root-__core-all-link' ..."
.PHONY: __logging___root-__core-all-link

build/koralle.js:  source/disclaimer.js libs/plankton.js temp/unlinked.js
	@ mkdir --parents build/
	@ cat source/disclaimer.js libs/plankton.js temp/unlinked.js > build/koralle.js

__root-__core-all-link-build:  __logging___root-__core-all-link-build temp/unlinked.js
	@ echo "				[log] <koralle> ... finished '__root-__core-all-link-build'"
.PHONY: __root-__core-all-link-build

__logging___root-__core-all-link-build: 
	@ echo "				[log] <koralle> processing '__root-__core-all-link-build' ..."
.PHONY: __logging___root-__core-all-link-build

temp/unlinked.js:  libs/plankton.d.ts source/base.ts source/helpers/message.ts source/helpers/cliout.ts source/helpers/graph.ts source/helpers/gnumake.ts source/helpers/ant.ts source/actions/_action.ts source/actions/exec.ts source/actions/echo.ts source/actions/mkdir.ts source/actions/touch.ts source/actions/copy.ts source/actions/move.ts source/actions/concat.ts source/actions/lessc.ts source/actions/babel.ts source/actions/tsc.ts source/actions/php.ts source/actions/gitpull.ts source/actions/schwamm.ts source/actions/schwamm-create.ts source/actions/schwamm-apply.ts source/tasks/_task.ts source/tasks/empty.ts source/tasks/group.ts source/tasks/script.ts source/tasks/copy.ts source/tasks/concat.ts source/tasks/lesscss.ts source/tasks/babel.ts source/tasks/typescript.ts source/tasks/php.ts source/tasks/schwamm.ts source/tasks/schwamm-create.ts source/tasks/schwamm-apply.ts source/outputs/_output.ts source/outputs/regular.ts source/outputs/ant.ts source/outputs/gnumake.ts source/project.ts source/main.ts
	@ mkdir --parents temp/
	@ tsc --allowUnreachableCode --target ES5 libs/plankton.d.ts source/base.ts source/helpers/message.ts source/helpers/cliout.ts source/helpers/graph.ts source/helpers/gnumake.ts source/helpers/ant.ts source/actions/_action.ts source/actions/exec.ts source/actions/echo.ts source/actions/mkdir.ts source/actions/touch.ts source/actions/copy.ts source/actions/move.ts source/actions/concat.ts source/actions/lessc.ts source/actions/babel.ts source/actions/tsc.ts source/actions/php.ts source/actions/gitpull.ts source/actions/schwamm.ts source/actions/schwamm-create.ts source/actions/schwamm-apply.ts source/tasks/_task.ts source/tasks/empty.ts source/tasks/group.ts source/tasks/script.ts source/tasks/copy.ts source/tasks/concat.ts source/tasks/lesscss.ts source/tasks/babel.ts source/tasks/typescript.ts source/tasks/php.ts source/tasks/schwamm.ts source/tasks/schwamm-create.ts source/tasks/schwamm-apply.ts source/outputs/_output.ts source/outputs/regular.ts source/outputs/ant.ts source/outputs/gnumake.ts source/project.ts source/main.ts --outFile temp/unlinked.js

__root-__core-all-documentation:  __logging___root-__core-all-documentation __root-__core-all-documentation-jsdoc __root-__core-all-documentation-diagram
	@ echo "			[log] <koralle> ... finished '__root-__core-all-documentation'"
.PHONY: __root-__core-all-documentation

__logging___root-__core-all-documentation: 
	@ echo "			[log] <koralle> processing '__root-__core-all-documentation' ..."
.PHONY: __logging___root-__core-all-documentation

__root-__core-all-documentation-jsdoc:  __logging___root-__core-all-documentation-jsdoc documentation/generated
	@ echo "				[log] <koralle> ... finished '__root-__core-all-documentation-jsdoc'"
.PHONY: __root-__core-all-documentation-jsdoc

__logging___root-__core-all-documentation-jsdoc: 
	@ echo "				[log] <koralle> processing '__root-__core-all-documentation-jsdoc' ..."
.PHONY: __logging___root-__core-all-documentation-jsdoc

documentation/generated:  build/koralle.js
	@ mkdir --parents documentation/
	@ /bin/sh tools/jsdoc.sh 'build/koralle.js' 'documentation/generated'

__root-__core-all-documentation-diagram:  __logging___root-__core-all-documentation-diagram documentation/structure/structure.svg
	@ echo "				[log] <koralle> ... finished '__root-__core-all-documentation-diagram'"
.PHONY: __root-__core-all-documentation-diagram

__logging___root-__core-all-documentation-diagram: 
	@ echo "				[log] <koralle> processing '__root-__core-all-documentation-diagram' ..."
.PHONY: __logging___root-__core-all-documentation-diagram

documentation/structure/structure.svg:  documentation/structure/structure.gv
	@ mkdir --parents documentation/structure/
	@ /bin/sh tools/graphviz.sh 'documentation/structure/structure.gv' 'documentation/structure/structure.svg'

