# Project "Koralle"
# This makefile was generated by Koralle 0.0.5

__default: __root
.PHONY: __default

__root: __dependencies __core
.PHONY: __root

__dependencies: __dependency_0 __dependency_1 __dependency_2 __dependency_3
.PHONY: __dependencies

__dependency_0: __logging___dependency_0
	@ koralle --target=gnumake --system=unix --raw ../plankton/base/project.json > /tmp/makefile
	@ make --no-print-directory --directory=../plankton/base/ --file=/tmp/makefile
.PHONY: __dependency_0

__logging___dependency_0:
	@ echo "[log] processing '__dependency_0' ..."
.PHONY: __logging___dependency_0

__dependency_1: __logging___dependency_1
	@ koralle --target=gnumake --system=unix --raw ../plankton/call/project.json > /tmp/makefile
	@ make --no-print-directory --directory=../plankton/call/ --file=/tmp/makefile
.PHONY: __dependency_1

__logging___dependency_1:
	@ echo "[log] processing '__dependency_1' ..."
.PHONY: __logging___dependency_1

__dependency_2: __logging___dependency_2
	@ koralle --target=gnumake --system=unix --raw ../plankton/string/project.json > /tmp/makefile
	@ make --no-print-directory --directory=../plankton/string/ --file=/tmp/makefile
.PHONY: __dependency_2

__logging___dependency_2:
	@ echo "[log] processing '__dependency_2' ..."
.PHONY: __logging___dependency_2

__dependency_3: __logging___dependency_3
	@ koralle --target=gnumake --system=unix --raw ../plankton/object/project.json > /tmp/makefile
	@ make --no-print-directory --directory=../plankton/object/ --file=/tmp/makefile
.PHONY: __dependency_3

__logging___dependency_3:
	@ echo "[log] processing '__dependency_3' ..."
.PHONY: __logging___dependency_3

__core: all
.PHONY: __core

all: __logging_all logic
.PHONY: all

__logging_all:
	@ echo "[log] <Koralle> processing 'all' ..."
.PHONY: __logging_all

logic: __logging_logic logic-ts build/koralle.js
.PHONY: logic

__logging_logic:
	@ echo "	[log] <Koralle> processing 'logic' ..."
.PHONY: __logging_logic

build/koralle.js: ../plankton/base/build/logic.js ../plankton/call/build/logic.js ../plankton/object/build/logic.js source/disclaimer.js temp/koralle.js
	@ mkdir -p build/
	@ cat ../plankton/base/build/logic.js ../plankton/call/build/logic.js ../plankton/object/build/logic.js source/disclaimer.js temp/koralle.js > build/koralle.js

logic-ts: __logging_logic-ts temp/koralle.js
.PHONY: logic-ts

__logging_logic-ts:
	@ echo "		[log] <Koralle> processing 'logic-ts' ..."
.PHONY: __logging_logic-ts

temp/koralle.js: source/base.ts source/helpers/message.ts source/helpers/cliout.ts source/helpers/graph.ts source/helpers/xml.ts source/helpers/gnumake.ts source/helpers/ant.ts source/helpers/misc.ts source/helpers/path.ts source/actions/action.ts source/actions/action_exec.ts source/actions/action_echo.ts source/actions/action_koralle.ts source/actions/action_build.ts source/actions/action_gnumake.ts source/actions/action_ant.ts source/actions/action_mkdir.ts source/actions/action_touch.ts source/actions/action_copy.ts source/actions/action_concat.ts source/actions/action_lessc.ts source/actions/action_babel.ts source/actions/action_tsc.ts source/actions/action_php.ts source/actions/action_gitpull.ts source/tasks/task.ts source/tasks/task_group.ts source/tasks/task_dependency.ts source/tasks/task_external.ts source/tasks/task_script.ts source/tasks/task_empty.ts source/tasks/task_copy.ts source/tasks/task_concat.ts source/tasks/task_lesscss.ts source/tasks/task_babel.ts source/tasks/task_typescript.ts source/tasks/task_php.ts source/targets/target.ts source/targets/target_regular.ts source/targets/target_ant.ts source/targets/target_gnumake.ts source/project.ts source/main.ts
	@ mkdir -p temp/
	@ tsc --allowUnreachableCode --target ES5 source/base.ts source/helpers/message.ts source/helpers/cliout.ts source/helpers/graph.ts source/helpers/xml.ts source/helpers/gnumake.ts source/helpers/ant.ts source/helpers/misc.ts source/helpers/path.ts source/actions/action.ts source/actions/action_exec.ts source/actions/action_echo.ts source/actions/action_koralle.ts source/actions/action_build.ts source/actions/action_gnumake.ts source/actions/action_ant.ts source/actions/action_mkdir.ts source/actions/action_touch.ts source/actions/action_copy.ts source/actions/action_concat.ts source/actions/action_lessc.ts source/actions/action_babel.ts source/actions/action_tsc.ts source/actions/action_php.ts source/actions/action_gitpull.ts source/tasks/task.ts source/tasks/task_group.ts source/tasks/task_dependency.ts source/tasks/task_external.ts source/tasks/task_script.ts source/tasks/task_empty.ts source/tasks/task_copy.ts source/tasks/task_concat.ts source/tasks/task_lesscss.ts source/tasks/task_babel.ts source/tasks/task_typescript.ts source/tasks/task_php.ts source/targets/target.ts source/targets/target_regular.ts source/targets/target_ant.ts source/targets/target_gnumake.ts source/project.ts source/main.ts --outFile temp/koralle.js

documentation: __logging_documentation jsdoc diagram
.PHONY: documentation

__logging_documentation:
	@ echo "	[log] <Koralle> processing 'documentation' ..."
.PHONY: __logging_documentation

jsdoc: __logging_jsdoc documentation/generated
.PHONY: jsdoc

__logging_jsdoc:
	@ echo "		[log] <Koralle> processing 'jsdoc' ..."
.PHONY: __logging_jsdoc

documentation/generated: build/koralle.js
	@ mkdir -p documentation/
	@ /bin/bash tools/jsdoc.sh build/koralle.js documentation/generated

diagram: __logging_diagram documentation/structure/structure.svg
.PHONY: diagram

__logging_diagram:
	@ echo "		[log] <Koralle> processing 'diagram' ..."
.PHONY: __logging_diagram

documentation/structure/structure.svg: documentation/structure/structure.gv
	@ mkdir -p documentation/structure/
	@ /bin/bash tools/graphviz.sh documentation/structure/structure.gv documentation/structure/structure.svg

